name: Run PHPUnit Tests

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Choose which test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'
          - 'feature'
          - 'unit'
      test_filter:
        description: 'Optional: Filter tests by name (e.g., ForgotPasswordTest, login)'
        required: false
        type: string
      specific_test_file:
        description: 'Optional: Path to a specific test file (e.g., tests/Feature/LoginTest.php)'
        required: false
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Or your desired PHP version
        extensions: mbstring, pdo_mysql, dom, gd, xml # Add any necessary extensions
        ini-values: post_max_size=256M, upload_max_filesize=256M
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Prepare Laravel Environment (if applicable)
      run: |
        cp .env.example .env
        php artisan key:generate
        # If you have a database, you might need to set it up here, e.g.:
        # php artisan migrate --seed --env=testing

    - name: Determine PHPUnit Command
      id: phpunit_command
      run: |
        TEST_COMMAND="vendor/bin/phpunit"

        if [ "${{ github.event.inputs.test_suite }}" == "feature" ]; then
          TEST_COMMAND="$TEST_COMMAND tests/Feature"
        elif [ "${{ github.event.inputs.test_suite }}" == "unit" ]; then
          TEST_COMMAND="$TEST_COMMAND tests/Unit"
        fi

        if [ -n "${{ github.event.inputs.test_filter }}" ]; then
          TEST_COMMAND="$TEST_COMMAND --filter '${{ github.event.inputs.test_filter }}'"
        fi

        if [ -n "${{ github.event.inputs.specific_test_file }}" ]; then
          # If a specific file is provided, it overrides suite and filter
          TEST_COMMAND="vendor/bin/phpunit ${{ github.event.inputs.specific_test_file }}"
        fi

        echo "phpunit_command=$TEST_COMMAND" >> $GITHUB_OUTPUT

    - name: Run PHPUnit Tests
      run: ${{ steps.phpunit_command.outputs.phpunit_command }}
