name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath, ctype, curl, dom, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Kunci SSH dari GitHub secrets
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: 22 # Port SSH yang benar
          script: |
            echo "PORT: 2086"  # Debugging
            # Uji koneksi SSH
            nc -zv ${{ secrets.SSH_HOST }} 22 || exit 1  # Akan gagal jika koneksi tidak berhasil

            
            echo "Koneksi SSH berhasil. Memulai deployment..."
  
            # Langkah-langkah deployment utama
            cd /home/xukxmbxe/RentalKamera
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            echo "${{ secrets.PROD_ENV_FILE }}" > .env
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            npm install
            npm run prod
  
    
